### ISSUE TITLE
[RealtekCardReader] compatibility with 0x0BDA 0x0177

### ISSUE THREAD

**Issue by dreamwhite** [0xFireWolf/RealtekCardReaderFriend#1]
Hi there,
first of all I'd like to thank you a lot for the effort you're putting onto the development of the main kext as well as the companion one.
I have a Dell Inspiron 5370 with a USB-based Realtek microSD card reader (`0x0BDA 0x0177`). It works fine on macOS but I'd like to know if RealtekCardReaderFriend can support it.
Greetings
dreamwhite

**Comment by 0xFireWolf** [comment]
Your card reader should be natively supported by Apple's driver.  
If it is listed by System Information, please upload your IOReg dump.

**Comment by dreamwhite** [comment]
Thank you so much for replying me. Well the card reader apparently is natively working but I don't see it onto System Information, where it should theoretically appear. Should I upload an IOReg dump in any case?
If so I'd like to avoid publishing my serials everywhere (ykwim) and I'd rather prefer a way like an email address, a Telegram username, a Matrix.org username or idk. Let me know what will be our communication channel and I'll send you the necessary stuff there.
Kind regards
dreamwhite

**Comment by 0xFireWolf** [comment]
Ah, my bad. It should be "If it is **NOT** listed by System Information, please upload your IOReg dump."

I dropped your a message on the Telegram.

**Comment by 0xFireWolf** [comment]
Resolved by the derived work [GenericCardReaderFriend](https://github.com/0xFireWolf/GenericCardReaderFriend).
