### ISSUE TITLE
Kernel Panic in Catalina for Realtek RTS5229

### ISSUE THREAD

**Issue by andreszerocross** [0xFireWolf/RealtekCardReaderFriend#4]
I got kernel panic with
1. Latest Release Lilu.kext + RealtekCardReader.kext
2. Latest commit Lilu.kext + Latest Commit RealtekCardReader.kext

Card reader is Realtek RTS5229

I upload this screenshot

![image](https://user-images.githubusercontent.com/9614101/144747245-e167b0ed-a839-4224-9a80-611f96675015.png)

**Comment by 0xFireWolf** [comment]
Your kernel panic is triggered by `RealtekCardReaderFriend`.
Please update the kext to the latest version as well or compile it against the latest Lilu by yourself.
