### ISSUE TITLE
Not working after updating to version 1.0.3

### ISSUE THREAD

**Issue by VictorxD70** [0xFireWolf/RealtekCardReaderFriend#8]
After updating to version 1.0.3 is no longer showing as a native card reader, but the card reader keeps working normally, I'm on Big Sur 11.6.7
![Captura de Tela 2022-06-25 às 14 24 58](https://user-images.githubusercontent.com/15053997/175784434-d487bfb9-fe10-4c49-800a-5d87a8c89571.png)
![Captura de Tela 2022-06-25 às 14 25 58](https://user-images.githubusercontent.com/15053997/175784444-abb512a1-d847-447b-81fd-e15ab6fcb213.png)

**Comment by 0xFireWolf** [comment]
You need the latest Lilu v1.6.1 as well.
